sudo: required
dist: trusty
language: node_js
node_js:
  - 10.2.1
env:
  matrix:
    - MONGODB_VERSION=4.0.x MONGODB_TOPOLOGY=standalone
addons:
  apt:
    packages:
      - build-essential
      - libkrb5-dev
      - libsecret-1-dev
      - libstdc++6
      - gnome-keyring
      - python-gnomekeyring
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> .npmrc
  - npm i -g npm@6.13.2
script: npm run ci
cache:
  directories:
    - $HOME/.electron
